#!/usr/bin/env bash
# Update the Homebrew tap formula (mrbrutti/homebrew-termus) so it points at
# the binaries from a given termus release.
#
# Usage:
#   scripts/update-homebrew-formula.sh <version>      # e.g. 0.2.0
#   scripts/update-homebrew-formula.sh latest         # latest published release
#
# What it does:
#   1. Resolves the release tag and looks up its binary tarball URLs.
#   2. Downloads each tarball and computes SHA-256.
#   3. Rewrites the local tap clone's Formula/termus.rb with the new URLs +
#      SHAs.
#   4. Commits and pushes (if there are changes).
#
# Tap clone path is configurable via env: HOMEBREW_TAP_DIR (defaults to the
# sibling directory ../homebrew-termus).

set -euo pipefail

ARG="${1:-latest}"
TAP_DIR="${HOMEBREW_TAP_DIR:-$(cd "$(dirname "$0")/../../homebrew-termus" && pwd)}"
REPO="mrbrutti/termus"

if ! command -v gh >/dev/null 2>&1; then
  echo "fatal: gh CLI not installed. brew install gh" >&2
  exit 1
fi
if [ ! -d "$TAP_DIR/Formula" ]; then
  echo "fatal: tap repo not found at $TAP_DIR (set HOMEBREW_TAP_DIR or clone mrbrutti/homebrew-termus there)" >&2
  exit 1
fi

# Resolve tag and version.
if [ "$ARG" = "latest" ]; then
  TAG="$(gh release view --repo "$REPO" --json tagName --jq .tagName)"
else
  TAG="$ARG"
  if [[ "$TAG" != v* ]]; then
    TAG="v$TAG"
  fi
fi
VERSION="${TAG#v}"
echo "→ updating formula to $TAG (version $VERSION)"

# Workspace for downloaded tarballs.
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Targets we ship binaries for. Keep in sync with .github/workflows/release.yml
# and the on_macos/on_linux blocks in the formula template.
# darwin-amd64 isn't here — Intel Mac users fall back to source build through
# the formula's on_intel block.
TARGETS=(darwin-arm64 linux-amd64)

declare -A SHA
for target in "${TARGETS[@]}"; do
  TAR="termus_${VERSION}_${target}.tar.gz"
  URL="https://github.com/${REPO}/releases/download/${TAG}/${TAR}"
  echo "  fetching $TAR"
  if ! curl -fsSL -o "$WORK/$TAR" "$URL"; then
    echo "fatal: download failed for $URL" >&2
    exit 1
  fi
  SHA[$target]="$(shasum -a 256 "$WORK/$TAR" | awk '{print $1}')"
  echo "    sha256=${SHA[$target]}"
done

# Also fetch the source tarball for the intel-Mac fallback path. GitHub
# auto-generates these for every tag at /archive/refs/tags/<TAG>.tar.gz.
SRC_TAR="termus-${VERSION}.tar.gz"
SRC_URL="https://github.com/${REPO}/archive/refs/tags/${TAG}.tar.gz"
echo "  fetching ${SRC_URL}"
if ! curl -fsSL -o "$WORK/$SRC_TAR" "$SRC_URL"; then
  echo "fatal: download failed for $SRC_URL" >&2
  exit 1
fi
SHA[source]="$(shasum -a 256 "$WORK/$SRC_TAR" | awk '{print $1}')"
echo "    source sha256=${SHA[source]}"

FORMULA="$TAP_DIR/Formula/termus.rb"

# Rewrite the formula in place. Generates a fresh file rather than sed-
# patching the old one — simpler, less fragile, easy to diff.
cat >"$FORMULA" <<RUBY
class Termus < Formula
  desc "Terminal music player that generates ambient, jazz, lofi, classical, and more in real time"
  homepage "https://mrbrutti.github.io/termus/"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/${REPO}/releases/download/${TAG}/termus_${VERSION}_darwin-arm64.tar.gz"
      sha256 "${SHA[darwin-arm64]}"
    end
    on_intel do
      # No prebuilt binary for Intel Macs yet — fall back to source build.
      url "https://github.com/${REPO}/archive/refs/tags/${TAG}.tar.gz"
      sha256 "${SHA[source]}"
      depends_on "go" => :build
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/${REPO}/releases/download/${TAG}/termus_${VERSION}_linux-amd64.tar.gz"
      sha256 "${SHA[linux-amd64]}"
    end
  end

  head "https://github.com/${REPO}.git", branch: "main"

  depends_on "go" => :build if build.head?

  def install
    # Build from source on intel-Mac (no binary shipped) and on HEAD installs.
    needs_build = build.head? || (OS.mac? && Hardware::CPU.intel?)
    if needs_build
      ldflags = %W[-s -w -X main.version=#{version}]
      system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"termus"), "./cmd/termus"
    else
      bin.install "termus"
    end
  end

  test do
    assert_match "algorithm name", shell_output("#{bin}/termus --help 2>&1", 0)
  end
end
RUBY

echo
echo "→ wrote $FORMULA"

# Commit + push if anything changed.
cd "$TAP_DIR"
if git diff --quiet -- Formula/termus.rb; then
  echo "→ no changes to commit"
  exit 0
fi

git add Formula/termus.rb
git commit -m "termus ${TAG}

URLs + SHA-256 hashes regenerated by scripts/update-homebrew-formula.sh.

darwin-arm64: ${SHA[darwin-arm64]}
darwin-amd64: ${SHA[darwin-amd64]}
linux-amd64:  ${SHA[linux-amd64]}"

echo
echo "→ committed. push with:"
echo "    git -C \"$TAP_DIR\" push origin main"
